---
- name: provision web server
  hosts: tag_group_web
  tasks:
    - name: install docker
      apt: 
        name: docker.io
      become: yes
    
    - name: start docker
      shell: |
        systemctl start docker
        systemctl enable docker

    - name: run image
      shell: docker run --name hello-world -d -p 80:80 -p 443:443 weichunnn/nginx-static
      become: yes