- name: provision web servers
  hosts: webservers
  tasks:
    - name: install pip3
      apt:
        update_cache: yes
        name: python3-pip
      become: true

    - name: install docker
      apt:
        name: docker.io
      become: yes

    - name: start docker
      shell: |
        systemctl enable docker
        systemctl start docker
      become: yes
