pipeline {
  agent any
  environment {
    imageName = "weichunnn/falcon-image-app:${env.BUILD_ID}"
    customImage = ""
  }

  stages {
    stage('start container for testing') {
      steps {
        dir('cicd-pipeline') {
          sh "docker compose rm -f; docker compose up -d images"
        }
      }
    }

    stage("run test") {
      steps {
        dir('cicd-pipeline') {
          sh "pip3 install -r requirements.txt; python3 -m pytest tests"
        }
      }
      post {
        success {
          dir('cicd-pipeline') {
            sh "docker compose down"
          }
        }
        failure {
          dir('cicd-pipeline') {
            sh "docker compose down"
          }
        }
      }
    }


    stage("build image") {
      steps {
        dir('cicd-pipeline') {
          script {
            customImage = docker.build(imageName)
          }
        }
      }
    }


    stage("push to registry") {
      when {
        branch "master"
      }
      steps {
        dir('cicd-pipeline') {
          script {
            docker.withRegistry('', 'Dockerhub') {
              customImage.push()
            }
          }
        }
      }
    }
  }
}